// <auto-generated />
using System;
using FitnessGymApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessGymApplication.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230105163511_TEST")]
    partial class TEST
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessGymApplication.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Freetrial")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Newsletter")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Phonenumber")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Coach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdSpeciality")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IdSpeciality");

                    b.ToTable("Coach");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = " Quentin",
                            IdSpeciality = 0,
                            LastName = "H.",
                            Photo = "/Assets/Images/Quentin H.jfif"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Léonce",
                            IdSpeciality = 0,
                            LastName = " L."
                        },
                        new
                        {
                            ID = 3,
                            FirstName = " Guillaume",
                            IdSpeciality = 0,
                            LastName = " J."
                        },
                        new
                        {
                            ID = 4,
                            FirstName = " Anthony",
                            IdSpeciality = 0,
                            LastName = " J."
                        },
                        new
                        {
                            ID = 5,
                            FirstName = " Romain",
                            IdSpeciality = 0,
                            LastName = "G."
                        },
                        new
                        {
                            ID = 6,
                            FirstName = "Lia",
                            IdSpeciality = 0,
                            LastName = "T."
                        },
                        new
                        {
                            ID = 7,
                            FirstName = "Florian",
                            IdSpeciality = 0,
                            LastName = "H."
                        },
                        new
                        {
                            ID = 8,
                            FirstName = "Mélodie",
                            IdSpeciality = 0,
                            LastName = "C."
                        },
                        new
                        {
                            ID = 9,
                            FirstName = "Nabil",
                            IdSpeciality = 0,
                            LastName = "C."
                        },
                        new
                        {
                            ID = 10,
                            FirstName = "Guillaume",
                            IdSpeciality = 0,
                            LastName = "P."
                        });
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 50,
                            Description = "Au sol sur le do, les genoux formant un angle un angle droit avec vos hanches. Ramenez votre buste vers le ciel tout en plaçant les mains au niveau de la nuque.",
                            Duration = 5,
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 100,
                            Description = "En position de planche frontale : sur la pointe des pieds, les mains bien à plat sur le sol, le dos droit et la tête dans le prolongement de votre colonne vertébrale. Ramenez ensuite les genoux à votre poitrine de façon alternée.",
                            Duration = 5,
                            Name = "Montain Climber"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 100,
                            Description = "Debout, l'espace entre votre deux pieds correspond à la largeur de vos épaules. Sautez en poussant les genoux vers l'extérieur. Lever les bras en même temps que vous sautez. Puis revenir en position initiale : debout, les bras le long du corps.",
                            Duration = 5,
                            Name = "Jumping jack"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 100,
                            Description = "En position de planche frontale, c'est-à-dire sur la pointe des pieds et mains à plat sur le sol, le dos droit et la tête dans le prolongement de votre colonne vertébrale. Ramenez la poitrine vers le sol en pliant les coudes puis tendez les bras. Restez bien gainé tout au long de l'exercice.",
                            Duration = 5,
                            Name = "Pompes Hiit"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 100,
                            Description = "Commencez en position debout, puis lever rapidement les genoux un après l'autre.",
                            Duration = 5,
                            Name = "Leg lift"
                        });
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCoach");

                    b.ToTable("FavoriteCoach");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdExercise");

                    b.ToTable("FavoriteExercise");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdLocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdLocation");

                    b.ToTable("FavoriteLocation");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteTrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdTrainingProgram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdTrainingProgram");

                    b.ToTable("FavoriteTrainingProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Formula", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Commitement")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Formula");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Commitement = 1,
                            Description = "L'abonnement mensuel CLASSIQUE FIT à 29€/mois vous donne accès à tous les clubs FITNESS GYM pour profiter de tous les appareils de musculations et cardio ainsi que de l'accès aux piscines dans les conditions du règlement intérieur. Cet abonnement est AVEC engagement sur une période de 12 mois et est valable de date à date.",
                            Name = "Classique fit",
                            Price = 29
                        },
                        new
                        {
                            ID = 2,
                            Commitement = 0,
                            Description = "L'abonnement mensuel CLASSIQUE FIT à 34€/mois vous donne accès à tous les clubs FITNESS GYM pour profiter de tous les appareils de musculations et cardio ainsi que de l'accès aux piscines dans les conditions du règlement intérieur. Cet abonnement est SANS engagement et valable de date à date. Seule la période en cours est due.",
                            Name = "Classique fit",
                            Price = 34
                        },
                        new
                        {
                            ID = 3,
                            Commitement = 1,
                            Description = "L'abonnement mensuel PREMIUM FIT à 36€/mois vous donne accès à tous les clubs FITNESS GYM pour y pratiquer les activités de sports de fitness et musculation, participer à une multitude de cours ainsi profiter de l'accès aux piscines dans les conditions du règlement intérieur. Cet abonnement est AVEC engagement sur une période de 12 mois et est valable de date à date.",
                            Name = "Premium fit",
                            Price = 36
                        },
                        new
                        {
                            ID = 4,
                            Commitement = 0,
                            Description = "L'abonnement mensuel PREMIUM FIT à 40€/mois vous donne accès à tous les clubs FITNESS GYM pour y pratiquer les activités de sports de fitness et musculation, participer à une multitude de cours ainsi profiter de l'accès aux piscines dans les conditions du règlement intérieur. Cet abonnement est SANS engagement et valable de date à date. Seule la période en cours est due.",
                            Name = "Premium fit",
                            Price = 40
                        },
                        new
                        {
                            ID = 5,
                            Commitement = 0,
                            Description = "Abonnement mensuel de 9€/mois sans engagement, sans période d'essai, seule la période en cours est due. Accès en illimités aux cours et programmes en ligne.",
                            Name = "No Gym No Problem",
                            Price = 9
                        },
                        new
                        {
                            ID = 6,
                            Commitement = 0,
                            Description = "Abonnement annuel de 29€/mois sans engagement, sans période d'essai, seule la période en cours est due. Accès en illimités aux cours et programmes en ligne.",
                            Name = "No Gym No Problem",
                            Price = 29
                        });
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaloriesBurnt")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.IndividualProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.Property<int>("IdTrainingProgram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdExercise");

                    b.HasIndex("IdTrainingProgram");

                    b.ToTable("IndividualProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "22 bis boulevard Saint Marcel",
                            City = "Paris",
                            MaxParticipants = 200,
                            Name = "Fitness Gym Austerlitz",
                            PostalCode = 75005
                        },
                        new
                        {
                            ID = 2,
                            Address = "4/6 Passage Louis Philippe",
                            City = "Paris",
                            MaxParticipants = 200,
                            Name = "Fitness Gym Bastille",
                            PostalCode = 75011
                        },
                        new
                        {
                            ID = 3,
                            Address = "123 Avenue de France ",
                            City = "Paris",
                            MaxParticipants = 150,
                            Name = "Fitness Gym BNF",
                            PostalCode = 75013
                        },
                        new
                        {
                            ID = 4,
                            Address = "21 rue de la banque",
                            City = "Paris",
                            MaxParticipants = 150,
                            Name = "Fitness Gym Opera",
                            PostalCode = 75002
                        },
                        new
                        {
                            ID = 5,
                            Address = "6 allée de la 2ème Division Blindée",
                            City = "Paris",
                            MaxParticipants = 150,
                            Name = "Fitness Gym Montparnasse",
                            PostalCode = 75014
                        },
                        new
                        {
                            ID = 6,
                            Address = "81 rue de Lagny ",
                            City = "Paris",
                            MaxParticipants = 250,
                            Name = "Fitness Gym Nation",
                            PostalCode = 75020
                        },
                        new
                        {
                            ID = 7,
                            Address = "44 rue de Clichy ",
                            City = "Paris",
                            MaxParticipants = 220,
                            Name = "Fitness Gym Saint-Lazarre",
                            PostalCode = 75009
                        },
                        new
                        {
                            ID = 8,
                            Address = "19, avenue de la Liberté",
                            City = "Nanterre",
                            MaxParticipants = 250,
                            Name = "Fitness Gym La défense",
                            PostalCode = 92000
                        },
                        new
                        {
                            ID = 9,
                            Address = "18-20, rue Auguste Perret",
                            City = "Villejuif",
                            MaxParticipants = 250,
                            Name = "Fitness Gym Villejuif",
                            PostalCode = 94800
                        },
                        new
                        {
                            ID = 10,
                            Address = "11, Rue Exelmans",
                            City = "Versailles",
                            MaxParticipants = 350,
                            Name = "Fitness Gym Versailles",
                            PostalCode = 78000
                        });
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Machine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.MachineLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IdLocation")
                        .HasColumnType("int");

                    b.Property<int>("IdMachine")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdLocation");

                    b.HasIndex("IdMachine");

                    b.ToTable("MachineLocation");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cancelled")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdSession");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int");

                    b.Property<int>("IdFormula")
                        .HasColumnType("int");

                    b.Property<int>("IdLocation")
                        .HasColumnType("int");

                    b.Property<int>("IdTrainingProgram")
                        .HasColumnType("int");

                    b.Property<string>("MaxParticipants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCoach");

                    b.HasIndex("IdFormula");

                    b.HasIndex("IdLocation");

                    b.HasIndex("IdTrainingProgram");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Speciality");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingProgram");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 750,
                            Description = "Fentes, squats, jumping jacks : plongez au cœur du Body Attack ! La dynamique de groupe vous donnera une énergie incroyable pour réaliser un entraînement de haute intensité. On y retrouve des mouvements athlétiques comme la course, les flexions ou les sauts, qui sont combinés à des exercices de renforcement comme les pompes. Chorégraphies et musiques donneront du rythme à vos fractionnés, pour une endurance décuplée..",
                            Duration = 45,
                            Intensity = 0,
                            Name = "Body Attack"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 500,
                            Description = "Bienvenue au  Body Pump ! Ce Group training LesMills tonifie et renforce le corps tout entier en permettant à vos muscles de se sculpter sans prendre de volume. Les mouvements sont simples et le nombre de répétitions est élevé : le secret des muscles fins et athlétiques.",
                            Duration = 45,
                            Intensity = 0,
                            Name = "Body Pump"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 500,
                            Description = "Fruit de la rencontre entre le step et le Body Pump, le Body Sculpt vous aide à redessiner votre silhouette. Elastiques, haltères et bâtons sont les accessoires-clés pour parvenir à cet objectif, dans le cadre d’un Group training complet et accessible à tous. Après un court échauffement, vous alternez toutes les 5 minutes entre exercices cardio et renforcement musculaire, avant de travailler les abdos et de vous étirer.",
                            Duration = 45,
                            Intensity = 0,
                            Name = "Body Sculpt"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 300,
                            Description = "Cours traditionnel de cuisses abdos fessiers permettant de renforcer ses muscles afin de consolider les articulations et de limiter les douleurs dorsales.",
                            Duration = 30,
                            Intensity = 0,
                            Name = "Cuisses Abdos Fessiers"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 700,
                            Description = "Le Hiit ou High Intensity Interval Training est un type d'entrainement bien connu pour son efficacité. C'est un cours où vous travaillerez principalement vos capacités cardio-vasculaires en association avec des mouvements de musculation. Le HIIT est un cours full body intense et complet qui permet aussi bien de travailler le renforcement musculaire que l'endurance, tout en se défoulant.",
                            Duration = 30,
                            Intensity = 0,
                            Name = "Hiit"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 550,
                            Description = "Initiez-vous à l’art du Step en enchaînant des chorégraphies sur et autour d’une marche à hauteur réglable, sur fond de musique rythmée. Montez, descendez, tournez : de la coordination, vous en aurez besoin à coups sûr ! Vous brûlerez aussi beaucoup de calories, quasiment sans vous en rendre compte tellement vous serez concentré sur vos mouvements !",
                            Duration = 45,
                            Intensity = 0,
                            Name = "Step"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 500,
                            Description = "Ce cours est un mix entre le Yoga et le Pilates. Il permet, grâce à des étirements, de travailler sa posture, en particulier celle du dos, en étirant la colonne vertébrale et en évitant le tassement des vertèbres. Les exercices effectués pendant la séance aident à augmenter la souplesse générale du corps en assouplissant et en renforçant l'élasticité des tendons et des muscles. Cela permet également de retrouver une silhouette affinée et plus harmonieuse.",
                            Duration = 60,
                            Intensity = 0,
                            Name = "Stretching"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 600,
                            Description = "Son nom signifie « Round Per minute », soit tour à la minute en français.  Entraîné par une musique électrisante, vous pédalez et donnez le meilleur de vous-même pour atteindre votre cible. Ici, l’objectif est de vous entraîner comme à l’extérieur mais de façon plus intensive.",
                            Duration = 45,
                            Intensity = 0,
                            Name = "RPM"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 400,
                            Description = "Entre dynamisme et calme, ce cours permet de gagner en force et en souplesse tout en respirant. Allez un peu plus loin chaque jour tout en respectant votre corps, en laissant frustration et égo de côté. Ressentez les postures du flow plutôt que d'essayer de dépasser vos limites. En apprenant à écouter son corps, on se connecte plus à son mental, pour plus de maîtrise de soi.",
                            Duration = 60,
                            Intensity = 0,
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 550,
                            Description = "De la chorégraphie, toujours et encore pour vous faire bouger sur des rythmes endiablés. De la salsa au merengue, en passant par la cumbia, le reggaeton, le kuduro… De la variété plus qu’il n’en faut au sein d’un Group training aussi efficace qu’amusant.",
                            Duration = 45,
                            Intensity = 0,
                            Name = "Zumba"
                        });
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Coach", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("IdSpeciality")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteCoach", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany("FavoriteCoach")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteExercise", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany("FavoriteExercice")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("IdExercise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteLocation", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany("FavoriteLocation")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.FavoriteTrainingProgram", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany("TrainingProgram")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.TrainingProgram", "TrainingProgram")
                        .WithMany()
                        .HasForeignKey("IdTrainingProgram")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Goal", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany("Goal")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.IndividualProgram", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Exercise", "Exercise")
                        .WithMany("IndividualPrograms")
                        .HasForeignKey("IdExercise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("IndividualPrograms")
                        .HasForeignKey("IdTrainingProgram")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.MachineLocation", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Location", "Location")
                        .WithMany("MachineLocation")
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Machine", "Machine")
                        .WithMany("MachineLocations")
                        .HasForeignKey("IdMachine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Reservation", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Session", "Session")
                        .WithMany("Reservations")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Session", b =>
                {
                    b.HasOne("FitnessGymApplication.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Formula", "Formula")
                        .WithMany()
                        .HasForeignKey("IdFormula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGymApplication.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("Sessions")
                        .HasForeignKey("IdTrainingProgram")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Formula");

                    b.Navigation("Location");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Client", b =>
                {
                    b.Navigation("FavoriteCoach");

                    b.Navigation("FavoriteExercice");

                    b.Navigation("FavoriteLocation");

                    b.Navigation("Goal");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Exercise", b =>
                {
                    b.Navigation("IndividualPrograms");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Location", b =>
                {
                    b.Navigation("MachineLocation");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Machine", b =>
                {
                    b.Navigation("MachineLocations");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.Session", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FitnessGymApplication.Models.TrainingProgram", b =>
                {
                    b.Navigation("IndividualPrograms");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
